CREATE TABLE USERS(
    ID INT,
    USERNAME VARCHAR(30),
    EMAIL VARCHAR(30),
    PASSW VARCHAR(40),
    NAME_ VARCHAR(30),
    COVERPIC VARCHAR(30),
    PROFILEPIC VARCHAR(30),
    CITY VARCHAR(30),
    WEBSITE VARCHAR(30),
    PRIMARY KEY(ID)
);

ALTER TABLE users
MODIFY passw varchar(400);


ALTER TABLE users
RENAME COLUMN id to user_id;

ALTER TABLE USERS MODIFY ID INT AUTO_INCREMENT;

INSERT INTO USERS (username,email,passw,name_) VALUE("kasdf", "a@gmail.com", "23ksdfjlas", "Bhaskar");

select * from users;

CREATE TABLE POSTS(
    ID INT AUTO_INCREMENT,
    DESCR VARCHAR(200),
    IMG VARCHAR(200),
    USERID INT,
    PRIMARY KEY(ID),
    CREATEDAT DATE,
    FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE
);


ALTER TABLE POSTS
MODIFY CREATEDAT DATETIME;


drop table POSTS;



CREATE TABLE COMMENTS(
    ID INT AUTO_INCREMENT,
    DESCR VARCHAR(200),
    CREATEDAT DATE,
    COMMENTUSERID INT,
    POSTID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (COMMENTUSERID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POSTID) REFERENCES POSTS(ID) ON DELETE CASCADE
);

ALTER TABLE COMMENTS
MODIFY CREATEDAT DATETIME;


SELECT * FROM COMMENTS;

drop table COMMENTS;

CREATE TABLE STORIES(
    ID INT,
    IMG VARCHAR(200),
    STORYUSERID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (STORYUSERID) REFERENCES USERS(ID) ON DELETE CASCADE
);
drop table STORIES;

drop table STORIES;

SELECT * FROM USERS;

CREATE TABLE RELATIONSHIPS(
    ID INT AUTO_INCREMENT,
    FOLLOWERUSERID INT,
    FOLLOWEDUSERID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (FOLLOWERUSERID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWEDUSERID) REFERENCES USERS(ID) ON DELETE CASCADE
);


select * from relationships;
INSERT INTO RELATIONSHIPS VALUE(19,24,23);


drop table RELATIONSHIPS;
CREATE TABLE LIKES(
    ID INT AUTO_INCREMENT,
    LIKEUSERID INT,
    POSTID INT,
    PRIMARY KEY(ID),
    FOREIGN KEY (LIKEUSERID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (POSTID) REFERENCES POSTS(ID) ON DELETE CASCADE
);

SELECT FOLLOWERUSERID FROM RELATIONSHIPS WHERE FOLLOWEDUSERID = 21;

drop table likes;
ALTER TABLE likes MODIFY ID INT AUTO_INCREMENT;

select * from likes;

